### WELCOME TO JEKYLL! 
### This configuration file control settings for the website. 





###
###  COURSE INFO
###


github_info:
    username:       lalmada1   # GitHub account name
    website-repo:   Coding-in-R-SPR-2023
    course-repo:    Coding-in-R-SPR-2023
 
description:        Coding in R for Policy Analytics 

course_url:         "https://lalmada1.github.io/Intro-to-Data-Science-Econ-4970"
title:              lalmada1   # GitHub account name

brand:
    image:          # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           "Coding in R"    # if the above "logo:" image variable  is not set, this text logo is displayed instead

###
###  YOUR PROGRAM INFO
###

program-logo:       "gsu-logo.png"

program-website:    
    
      
###
### COURSE INSTRUCTOR:
###

author:
    name:       Lorenzo Almada 
    github:     lalmada1   # Github username for avatar




###
### NAVIGATION BAR
###

header:
- title: Syllabus
  url:
- title: Schedule
  #url: schedule/
# - title: Textbook
#   url: https://ds4ps.org/dp4ss/#dp4ss-data-programming-for-the-social-sciences
- title: Resources
  #url: resources/
- title: Get Help
  #url: help/


# set navbar color at assets/css/custom.css under default_nav and footer background-color
 



























# IGNORE THESE SETTINGS


# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/


# Social icons displayed in footer
social:
    email:
    website:
    facebook:
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:
    linkedin:
    pinterest:
    twitter:
    vimeo:
    youtube:

# Twitter share button
twitter_username:


# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true
